#!/bin/bash
# configure.sh - Interactive Makefile generator for trimmer

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${CYAN}${BOLD}"
echo "╔═══════════════════════════════════════════╗"
echo "║     Trimmer Build Configuration Script    ║"
echo "╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# Check for sudo
HAS_SUDO=0
if command -v sudo &> /dev/null; then
    HAS_SUDO=1
    echo -e "${GREEN}✓ sudo found${NC}"
else
    echo -e "${YELLOW}⚠ sudo not found - install target will require root${NC}"
fi
echo ""

# Defaults
CC="gcc"
OPTLEVEL="-O2"
DEBUG=""
EXTRA_FLAGS=""

# Compiler
echo -e "${YELLOW}[1/4] Select your compiler:${NC}"
echo "  1) gcc (default)"
echo "  2) clang"
echo "  3) tcc"
echo "  4) Other"
read -p "Choice [1]: " cc_choice

case "$cc_choice" in
    2) CC="clang" ;;
    3) CC="tcc" ;;
    4) read -p "Enter compiler: " CC ;;
    *) CC="gcc" ;;
esac
echo -e "${GREEN}→ $CC${NC}\n"

# Optimization
echo -e "${YELLOW}[2/4] Optimization level:${NC}"
echo "  1) -O0 (none)"
echo "  2) -O1 (basic)"
echo "  3) -O2 (balanced) [default]"
echo "  4) -O3 (aggressive)"
echo "  5) -Os (size)"
echo "  6) -Ofast (fastest, may cause inaccuracy)"
read -p "Choice [3]: " opt_choice

case "$opt_choice" in
    1) OPTLEVEL="-O0" ;;
    2) OPTLEVEL="-O1" ;;
    4) OPTLEVEL="-O3" ;;
    5) OPTLEVEL="-Os" ;;
    6) OPTLEVEL="-Ofast" ;;
    *) OPTLEVEL="-O2" ;;
esac
echo -e "${GREEN}→ $OPTLEVEL${NC}\n"

# Debug symbols
echo -e "${YELLOW}[3/4] Debug symbols:${NC}"
echo "  1) None [default]"
echo "  2) -g (standard)"
echo "  3) -g3 (maximum)"
echo "  4) -ggdb (GDB-optimized)"
read -p "Choice [1]: " debug_choice

case "$debug_choice" in
    2) DEBUG="-g" ;;
    3) DEBUG="-g3" ;;
    4) DEBUG="-ggdb" ;;
    *) DEBUG="" ;;
esac
[ -n "$DEBUG" ] && echo -e "${GREEN}→ $DEBUG${NC}\n" || echo -e "${GREEN}→ none${NC}\n"

# Extra flags (multi-select)
echo -e "${YELLOW}[4/4] Additional flags (comma-separated, e.g. 1,3):${NC}"
echo "  1) Warnings (-Wall -Wextra)"
echo "  2) Pedantic (-Werror -pedantic)"
echo "  3) LTO (-flto)"
echo "  4) Native arch (-march=native -mtune=native)"
echo "  5) Manual entry"
echo "  6) None [default]"
read -p "Choice [6]: " extra_choice

# Parse multi-select
WARNINGS=""
PEDANTIC=""
LTO=""
NATIVE=""

IFS=',' read -ra CHOICES <<< "$extra_choice"
for choice in "${CHOICES[@]}"; do
    choice=$(echo "$choice" | tr -d ' ')
    case "$choice" in
        1) WARNINGS="-Wall -Wextra" ;;
        2) PEDANTIC="-Werror -pedantic" ;;
        3) LTO="-flto" ;;
        4) NATIVE="-march=native -mtune=native" ;;
        5)
            echo -e "\n${CYAN}Enter your flags:${NC}"
            read -p "> " MANUAL
            EXTRA_FLAGS="$MANUAL"
            ;;
    esac
done

# Combine selected flags
[ -n "$WARNINGS" ] && EXTRA_FLAGS="$EXTRA_FLAGS $WARNINGS"
[ -n "$PEDANTIC" ] && EXTRA_FLAGS="$EXTRA_FLAGS $PEDANTIC"
[ -n "$LTO" ] && EXTRA_FLAGS="$EXTRA_FLAGS $LTO"
[ -n "$NATIVE" ] && EXTRA_FLAGS="$EXTRA_FLAGS $NATIVE"
EXTRA_FLAGS=$(echo "$EXTRA_FLAGS" | xargs)

[ -n "$EXTRA_FLAGS" ] && echo -e "${GREEN}→ $EXTRA_FLAGS${NC}\n" || echo -e "${GREEN}→ none${NC}\n"

# Build CFLAGS
CFLAGS="$OPTLEVEL"
[ -n "$DEBUG" ] && CFLAGS="$CFLAGS $DEBUG"
[ -n "$EXTRA_FLAGS" ] && CFLAGS="$CFLAGS $EXTRA_FLAGS"
CFLAGS="$CFLAGS -pthread"

# Install command based on sudo availability
if [ $HAS_SUDO -eq 1 ]; then
    INSTALL_CMD="sudo mv \$(TARGET) /usr/local/bin/"
    UNINSTALL_CMD="sudo rm -f /usr/local/bin/\$(TARGET)"
else
    INSTALL_CMD="mv \$(TARGET) /usr/local/bin/"
    UNINSTALL_CMD="rm -f /usr/local/bin/\$(TARGET)"
fi

# Generate Makefile
echo -e "${CYAN}${BOLD}Generating Makefile...${NC}"

cat > Makefile << EOF
# ═══════════════════════════════════════════════════════════════════════════════
# ╔═════════════════════════════════════════════════════════════════════════════╗
# ║                                                                             ║
# ║                              T R I M M E R                                  ║
# ║                                                                             ║
# ║         A high-performance, streaming, fuzzy-logic whitespace cleaner      ║
# ║                                                                             ║
# ╠═════════════════════════════════════════════════════════════════════════════╣
# ║                                                                             ║
# ║   This Makefile was auto-generated by configure.sh on $(date '+%Y-%m-%d %H:%M')          ║
# ║                                                                             ║
# ║   Configuration:                                                            ║
# ║     • Compiler ............ $CC$(printf '%*s' $((40 - ${#CC})) '')║
# ║     • Optimization ........ $OPTLEVEL$(printf '%*s' $((40 - ${#OPTLEVEL})) '')║
# ║     • Debug ............... ${DEBUG:-none}$(printf '%*s' $((40 - ${#DEBUG:-none})) '')║
# ║                                                                             ║
# ╚═════════════════════════════════════════════════════════════════════════════╝
# ═══════════════════════════════════════════════════════════════════════════════

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                            Compiler Settings                                │
# └─────────────────────────────────────────────────────────────────────────────┘
CC = $CC
CFLAGS = $CFLAGS
LDFLAGS = -pthread

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                              Build Targets                                  │
# └─────────────────────────────────────────────────────────────────────────────┘
TARGET = trim
SRC = trim.c
OBJ = \$(SRC:.c=.o)

# ┌─────────────────────────────────────────────────────────────────────────────┐
# │                             Phony Targets                                   │
# │                                                                             │
# │   all ........... Build the executable                                      │
# │   clean ......... Remove build artifacts                                    │
# │   install ....... Install to /usr/local/bin                                 │
# │   uninstall ..... Remove from /usr/local/bin                                │
# │   debug ......... Build with debug symbols                                  │
# │   release ....... Build with max optimization                               │
# │                                                                             │
# └─────────────────────────────────────────────────────────────────────────────┘
.PHONY: all clean install uninstall debug release

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                              Default Target                                 │
# ╰─────────────────────────────────────────────────────────────────────────────╯
all: \$(TARGET)

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                               Link Stage                                    │
# │                                                                             │
# │   Links all object files into the final executable.                         │
# │   The \$@ expands to the target name, \$^ expands to all prerequisites.      │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
\$(TARGET): \$(OBJ)
	\$(CC) \$(CFLAGS) -o \$@ \$^ \$(LDFLAGS)

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                              Compile Stage                                  │
# │                                                                             │
# │   Pattern rule for compiling .c files to .o object files.                   │
# │   The -c flag tells the compiler to generate object code only.              │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
%.o: %.c
	\$(CC) \$(CFLAGS) -c -o \$@ \$<

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                                Cleanup                                      │
# │                                                                             │
# │   Removes the compiled binary and all intermediate object files.            │
# │   Use this to force a complete rebuild.                                     │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
clean:
	rm -f \$(TARGET) \$(OBJ)

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                             Installation                                    │
# │                                                                             │
# │   Installs the trimmer binary to /usr/local/bin for system-wide access.    │
# │   Requires appropriate permissions (sudo if available).                     │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
install: \$(TARGET)
	$INSTALL_CMD

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                            Uninstallation                                   │
# │                                                                             │
# │   Removes the trimmer binary from /usr/local/bin.                           │
# │   Reverses the install target.                                              │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
uninstall:
	$UNINSTALL_CMD

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                              Debug Build                                    │
# │                                                                             │
# │   Builds with maximum debug information for use with GDB or other           │
# │   debuggers. Adds -g3 flag and defines DEBUG macro.                         │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
debug:
	\$(MAKE) CFLAGS="\$(CFLAGS) -g3 -DDEBUG"

# ╭─────────────────────────────────────────────────────────────────────────────╮
# │                             Release Build                                   │
# │                                                                             │
# │   Builds with aggressive optimizations for maximum performance.             │
# │   Enables LTO, native architecture tuning, and strips debug info.           │
# │                                                                             │
# │   Flags used:                                                               │
# │     -O3 .............. Aggressive optimization                              │
# │     -flto ............ Link-time optimization                               │
# │     -march=native .... Target current CPU architecture                      │
# │     -mtune=native .... Tune for current CPU                                 │
# │     -DNDEBUG ......... Disable assertions                                   │
# │                                                                             │
# ╰─────────────────────────────────────────────────────────────────────────────╯
release:
	\$(MAKE) CFLAGS="-O3 -flto -march=native -mtune=native -DNDEBUG -pthread"

# ═══════════════════════════════════════════════════════════════════════════════
#                                 End of Makefile
# ═══════════════════════════════════════════════════════════════════════════════
EOF

echo ""
echo -e "${GREEN}${BOLD}╔═══════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║             Makefile generated!           ║${NC}"
echo -e "${GREEN}${BOLD}╚═══════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Summary:${NC}"
echo -e "  Compiler: ${BOLD}$CC${NC}"
echo -e "  CFLAGS:   ${BOLD}$CFLAGS${NC}"
echo ""
echo -e "${YELLOW}Commands:${NC}"
echo "  make          # Build"
echo "  make clean    # Clean"
echo "  make install  # Install to /usr/local/bin"
echo ""
